/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrintersRouteImport } from './routes/printers'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RevenueRouteImport } from './routes/revenue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintersRoute = PrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estimator': typeof EstimatorRoute
  '/inventory': typeof InventoryRoute
  '/operations': typeof OperationsRoute
  '/orders': typeof OrdersRoute
  '/printers': typeof PrintersRoute
  '/products': typeof ProductsRoute
  '/queue': typeof QueueRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estimator': typeof EstimatorRoute
  '/inventory': typeof InventoryRoute
  '/operations': typeof OperationsRoute
  '/orders': typeof OrdersRoute
  '/printers': typeof PrintersRoute
  '/products': typeof ProductsRoute
  '/queue': typeof QueueRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estimator': typeof EstimatorRoute
  '/inventory': typeof InventoryRoute
  '/operations': typeof OperationsRoute
  '/orders': typeof OrdersRoute
  '/printers': typeof PrintersRoute
  '/products': typeof ProductsRoute
  '/queue': typeof QueueRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estimator'
    | '/inventory'
    | '/operations'
    | '/orders'
    | '/printers'
    | '/products'
    | '/queue'
    | '/revenue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estimator'
    | '/inventory'
    | '/operations'
    | '/orders'
    | '/printers'
    | '/products'
    | '/queue'
    | '/revenue'
  id:
    | '__root__'
    | '/'
    | '/estimator'
    | '/inventory'
    | '/operations'
    | '/orders'
    | '/printers'
    | '/products'
    | '/queue'
    | '/revenue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstimatorRoute: typeof EstimatorRoute
  InventoryRoute: typeof InventoryRoute
  OperationsRoute: typeof OperationsRoute
  OrdersRoute: typeof OrdersRoute
  PrintersRoute: typeof PrintersRoute
  ProductsRoute: typeof ProductsRoute
  QueueRoute: typeof QueueRoute
  RevenueRoute: typeof RevenueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printers': {
      id: '/printers'
      path: '/printers'
      fullPath: '/printers'
      preLoaderRoute: typeof PrintersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstimatorRoute: EstimatorRoute,
  InventoryRoute: InventoryRoute,
  OperationsRoute: OperationsRoute,
  OrdersRoute: OrdersRoute,
  PrintersRoute: PrintersRoute,
  ProductsRoute: ProductsRoute,
  QueueRoute: QueueRoute,
  RevenueRoute: RevenueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
